#!/usr/bin/env python3
"""Emit trap stubs for every Xbox 360 kernel import the recompiled code calls.

XenonRecomp declares each import as an extern PPCFunc named __imp__<Name> and
leaves the definition to the runtime. Anything we have not implemented yet must
fail loudly the first time the game calls it -- a stub that quietly returns 0
would send the game down a wrong path far from the real cause.

Stubs are generated rather than committed because the import list is derived
from the user's own copy of the game.

Usage: gen_import_stubs.py <ppc_func_mapping.cpp> <output.cpp>
"""
import re
import sys


def main():
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)

    mapping_path, out_path = sys.argv[1], sys.argv[2]

    with open(mapping_path) as f:
        names = sorted(set(re.findall(r"\b(__imp__\w+)\b", f.read())))

    if not names:
        raise SystemExit(f"no __imp__ symbols found in {mapping_path}")

    with open(out_path, "w") as out:
        out.write(
            "// Generated by tools/gen_import_stubs.py -- do not edit.\n"
            '#include "import_stub.h"\n\n'
        )
        for name in names:
            # GEARS_IMPORT_IMPLEMENTED lets a hand-written implementation in
            # another translation unit claim the name; the stub then drops out.
            guest = name[len("__imp__"):]
            out.write(f"#ifndef GEARS_IMPORT_IMPLEMENTED_{guest}\n")
            out.write(f"GEARS_UNIMPLEMENTED_IMPORT({guest})\n")
            out.write("#endif\n")

    print(f"generated {len(names)} import stubs -> {out_path}")


if __name__ == "__main__":
    main()
