#!/usr/bin/env python3
"""Publish the current Git revision as a generated C++ header.

The target that calls this tool runs before every runtime build.  The file is
rewritten only when its contents change, so a new commit invalidates main.cpp
while repeated builds of one commit remain no-ops.
"""

import argparse
import subprocess
import sys
import tempfile
from pathlib import Path


def read_revision(repository: Path) -> str:
    result = subprocess.run(
        ["git", "-C", str(repository), "rev-parse", "--short", "HEAD"],
        check=False,
        capture_output=True,
        text=True,
    )
    revision = result.stdout.strip()
    if result.returncode != 0 or not revision:
        return "unknown"
    if any(character not in "0123456789abcdefABCDEF" for character in revision):
        raise RuntimeError(f"git returned an invalid revision {revision!r}")
    return revision.lower()


def render_header(revision: str) -> str:
    return (
        "// Generated by tools/write_build_revision.py; do not edit.\n"
        "#pragma once\n\n"
        f'#define GEARS_BUILD_REVISION "{revision}"\n'
    )


def publish_header(output: Path, revision: str) -> bool:
    contents = render_header(revision)
    if output.is_file() and output.read_text() == contents:
        return False

    output.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        mode="w", encoding="utf-8", dir=output.parent, delete=False
    ) as temporary:
        temporary.write(contents)
        temporary_path = Path(temporary.name)
    temporary_path.replace(output)
    return True


def selftest(root: Path) -> int:
    scratch = root / "scratch"
    scratch.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="build-revision-selftest-", dir=scratch) as name:
        repository = Path(name) / "repository"
        output = Path(name) / "generated" / "build_revision.h"
        repository.mkdir()

        commands = [
            ["git", "init", "-q"],
            ["git", "config", "user.name", "Build Revision Selftest"],
            ["git", "config", "user.email", "selftest@example.invalid"],
        ]
        for command in commands:
            subprocess.run(command, cwd=repository, check=True)

        if read_revision(repository) != "unknown":
            raise RuntimeError("a repository without a commit did not publish unknown")

        tracked = repository / "tracked.txt"
        tracked.write_text("first\n")
        subprocess.run(["git", "add", "tracked.txt"], cwd=repository, check=True)
        subprocess.run(["git", "commit", "-q", "-m", "first"], cwd=repository, check=True)

        first_revision = read_revision(repository)
        if first_revision == "unknown" or not publish_header(output, first_revision):
            raise RuntimeError("the first committed revision was not published")
        first_mtime = output.stat().st_mtime_ns
        if publish_header(output, first_revision) or output.stat().st_mtime_ns != first_mtime:
            raise RuntimeError("an unchanged revision rewrote the generated header")

        tracked.write_text("second\n")
        subprocess.run(["git", "commit", "-q", "-am", "second"], cwd=repository, check=True)
        second_revision = read_revision(repository)
        if second_revision == first_revision or not publish_header(output, second_revision):
            raise RuntimeError("a new commit did not update the generated header")
        if f'"{second_revision}"' not in output.read_text():
            raise RuntimeError("the generated header does not contain the new revision")

    print(
        "build revision selftest passed: a commit changes the header and an "
        "unchanged revision preserves it"
    )
    return 0


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repository", type=Path)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--selftest", action="store_true")
    arguments = parser.parse_args(argv[1:])

    root = Path(__file__).resolve().parents[1]
    if arguments.selftest:
        if arguments.repository or arguments.output:
            parser.error("--selftest does not accept --repository or --output")
        return selftest(root)
    if arguments.repository is None or arguments.output is None:
        parser.error("--repository and --output are required")

    try:
        revision = read_revision(arguments.repository)
        changed = publish_header(arguments.output, revision)
    except (OSError, RuntimeError) as error:
        print(f"build revision generation failed: {error}", file=sys.stderr)
        return 1
    if changed:
        print(f"generated {arguments.output} for {revision}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
